### ISSUE TITLE
Sitemap sorting

### ISSUE THREAD

**Issue by rudolfbyker** [harlan-zw/nuxt-simple-sitemap#144]
### Details

Is it possible to influence or disable the sorting of entries? In my `/server/api/_sitemap-urls.ts` file, I provide my URLs in this order:

- /en/comment/1
- /en/comment/2
- /en/comment/3
- ...

but in the final sitemap file, it ends up in this order:

- /en/comment/1
- /en/comment/10
- /en/comment/100
- ...

I would like to keep my original order.

**Comment by harlan-zw** [comment]
Hi @rudolfbyker, thanks for flagging this.

I've pushed up a fix so that it sorts these URLs more logically for numbers (see https://github.com/harlan-zw/nuxt-simple-sitemap/commit/611006b8207bd64a7b2a8b73851802de3dde3e0c) - available in v3.3.6.

Do you think this solves the issue or you'd still like to disable the inherit sorting?

**Comment by rudolfbyker** [comment]
Thanks for your time and effort! I would definitely like to disable sorting completely. This also relates to my other issue #143 where I would expect the generator order to be preserved :)

**Comment by harlan-zw** [comment]
Fair enough, I've added the module option `sortEntries` which you can use to opt-out of the sorting.

```ts
export default defineNuxtConfig({
  sitemap: {
     sortEntries: false
  }
})
```

Let me know if you have any issues with it.
