### ISSUE TITLE
How to see if priority works?

### ISSUE THREAD

**Issue by gyhyfj** [harlan-zw/nuxt-simple-sitemap#46]
### Details

My `nuxt.config.ts` is 
```ts
sitemap: {
    siteUrl: 'https://xxx',
    urls: () => posts.map(item => ({
        loc: `/post/${item[0]}`,
        lastmod: new Date(),
        priority: 0.6,
      })),
  },
```
Then I check `https://xxx/sitemap.xml`, I can only see 3 columns named `URL` `Images` and `Last Mod.`
How can I know if priority work? Is other pages with priority 1 by default?

**Comment by harlan-zw** [comment]
Hi @gyhyfj, sorry for the delay.

This is because the stylesheet is enabled. You can view the source of the sitemap by right-clicking and viewing the source. The source is how robots will intepret the sitemap, the stylesheet just makes reading it easier for humans.

If you'd like to disable the stylesheet you can pass  `xsl: false`.

Let me know if that isn't clear :)

**Comment by gyhyfj** [comment]
Yes got it, thank you!
