### ISSUE TITLE
Customizing Sitemap URL

### ISSUE THREAD

**Issue by LettyCoach** [harlan-zw/nuxt-simple-sitemap#99]
### Details

Hello.
Nice to meet you.

Currently I am building web application using Nuxt3 and try to use this `nuxt-simple-sitemap` package for dynamic sitemap generation.

After integration, I can access sitemap by enter http://localhost:3000/sitemap.xml  and it redirects to http://localhost:3000/sitemap_index.xml.

I 'd like to change this sitemap url.  For example: http://localhost:3000/myapp/sitemap.xml,  http://localhost:3000/myapp/sitemap_index.xml  

Is there anyway for above requirement with this package?

I will wait for you.
Best regards.

**Comment by harlan-zw** [comment]
Hi @LettyCoach 

Maybe you want to make use of the `baseURL` feature from Nuxt? This should do what you've described.

```ts
export default defineNuxtConfig(() => {
     app: {
       baseURL: '/my-app',
    },
})
```

Otherwise, you can use the single sitemap mode and use the `sitemapName` config.

If both of these don't apply, I can look at supporting a config to set the sitemap index name for you.

**Comment by harlan-zw** [comment]
Going to close, feel free to re-open if the above doesn't answer your question.
